
# Perfil de Desarrollo
server.port=8080

# Logs detallados para desarrollo
logging.level.root=INFO
logging.level.com.example.CatalogoOnline=DEBUG
logging.level.org.springframework.web=DEBUG

# Mostrar SQL (si usas JPA más adelante)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true