# Perfil de Testing
server.port=8081

# Logs mínimos para testing
logging.level.root=WARN
logging.level.com.example.CatalogoOnline=INFO

# Deshabilitar Swagger en tests
springdoc.swagger-ui.enabled=false