
# Nombre de la aplicación
spring.application.name=CatalogoOnline

# Perfil activo por defecto
spring.profiles.active=dev

# Puerto del servidor
server.port=8080

# Configuración de Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Logs generales
logging.level.root=INFO
logging.level.com.example.CatalogoOnline=DEBUG